package main

import (
	"testing"
)

func TestFindUniqueAntinodesPart1(t *testing.T) {
	tests := []struct {
		input    string
		expected int
	}{
		{
			`............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............`, 14},
	}

	for _, test := range tests {
		result, _ := FindUniqueAntinodes(ConvertToPositions(test.input))

		if result != test.expected {
			t.Errorf("TestFindUniqueAntinodesPart1(%v) = %v; want %v", test.input, result, test.expected)
		}
	}
}

func TestFindUniqueAntinodesPart2(t *testing.T) {
	tests := []struct {
		input    string
		expected int
	}{
		{
			`............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............`, 34},
	}

	for _, test := range tests {
		result, _ := FindUniqueAntinodesInline(ConvertToPositions(test.input))

		if result != test.expected {
			t.Errorf("TestFindUniqueAntinodesPart2(%v) = %v; want %v", test.input, result, test.expected)
		}
	}
}
